name: 'dbt_shopflow'
version: '1.0.0'
config-version: 2

profile: 'shopflow'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt_shopflow:
    staging:
      +schema: staging
      +materialized: view
    curated:
      +schema: curated
      +materialized: table
      
vars:
  raw_schema: 'raw'
