version: 2

sources:
  - name: rds
    # Point to ingested raw schema in local Postgres
    schema: raw
    tables:
      - name: customers
        description: "RDS customers table"
      - name: orders
        description: "RDS orders table"
      - name: products
        description: "RDS products table"
      - name: events
        description: "RDS events table"
      - name: inventory
        description: "RDS inventory table"

  - name: raw_api
    # raw layer where API Parquet or ingested API table lives (keep database out to use target DB)
    schema: raw
    tables:
      - name: support_tickets
        description: "Support tickets loaded from API (Parquet / external table)"
